import os
from PIL import Image
from botcity.core import DesktopBot
import pyautogui as py
import keyboard
from plyer import notification  # Para enviar notificações
import time
import threading
#from input_boletos import aguardar_digitar, aguardar_digitar_texto, comportamento_para_sim, aguardar_tecla_insert, finalizar_processo




class Bot(DesktopBot):
    reiniciar_solicitado = False  # Variável para evitar múltiplos reinícios
    
    def __init__(self):
        super().__init__()
        if not hasattr(self, 'monitorando_teclas'):
            self.monitorando_teclas = True
            #threading.Thread(target=self.monitorar_teclas, daemon=True).start()
            

bancos = {
            654:	("A.J. RENNER S.A.", None),
            246:	("ABC-BRASIL S.A.", None),
            213:	("ARBI S.A.", None),
            19:	    ("AZTECA DO BRASIL , None),A.", None),
            25:	    ("BANCO ALFA", None),
            241:    ("Banco Classico S.A", None),
            83:	    ("BANCO DA CHINA BRASIL S.A.", None),
            300:    ("BANCO DE LA NACION ARGENTINA", None),
            495:    ("BANCO DE LA PROVINCIA DE BUENOS AIRES", None),
            494:    ("BANCO DE LA REPUBLICA ORIENTAL DEL URUGUAY", None),
            1:      ("BANCO DO BRASIL", None),
            37:	    ("BANCO DO ESTADO DO PARÁ S.A", None),
            456:	("BANCO TOKYO MITSUBISH UFJ BRASIL S.A", None),
            370:	("BANCO WESTLB DO BRASIL", None),
            756:	("SICOOB", None),
            47:	    ("BANESE", None),
            33:	    ("SANTANDER", None),
            21:	    ("BANESTES", None),
            719:	("BANIF-BANCO INTERNACIONAL DO FUNCHAL (BRASIL) S.A", None),
            755:	("BANK OF AMERICA MERRILL LYNCH BANCO MULTIPLO S.A.", None),
            41:	    ("BANRISUL", None),
            740:	("BARCLAYS S.A.", None),
            3:      ("BASA", None),
            107:	("BBM S.A", None),
            81:	    ("BBN BANCO BRASILEIRO DE NEGOCIOS S.A", None),
            250:	("BCV - BANCO DE CREDITO E VAREJO S.A", None),
            36:	    ("BEM", None),
            122:	("BERJ S.A", None),
            78:	    ("BES INVESTIMENTO DO BRASIL SA - BANCO DE INVESTIM.", None),
            739:	("BGN S.A.", None),
            320:	("BIC BANCO", None),
            96:	    ("BM&F DE SERV. DE LIQUIDACAO E CUSTODIA S.A", None),
            394:	("BMC S.A.", None),
            318:	("BMG S.A.", None),
            4:      ("BNB", None),
            752:	("BNP PARIBAS BRASIL S.A", None),
            17:	    ("BNY MELLON S.A.", None),
            248:	("BOA VISTA INTERATLANTICO S.A", None),
            218:	("BONSUCESSO S.A.", None),
            69:	    ("BPN BRASIL BANCO MULTIPLO S.A", None),
            65:	    ("BRACCE S.A.", None),
            237:	("BRADESCO", None),
            225:	("BRASCAN S.A.", None),
            125:	("BRASIL PLURAL S.A. BANCO MULTIPLO", None),
            70:	    ("BRB", None),
            92:	    ("BRICKELL S A CREDITO, FINANCIAMENTO E INVESTIMENTO", None),
            208:	("BTG PACTUAL S.A.", None),
            263:	("CACIQUE S.A.", None),
            104:	("CAIXA ECON. FEDERAL", None),
            473:	("CAIXA GERAL - BRASIL S.A.", None),
            412:	("CAPITAL S.A.", None),
            40:	    ("CARGILL S.A", None),
            112:	("CC UNICRED BRASIL CENTRAL", None),
            84:	    ("CC UNIPRIME NORTE DO PARANA", None),
            114:	("CECOOPES-CENTRAL DAS COOP DE ECON E CRED MUTUO", None),
            85:	    ("AILOS", None),
            266:	("CEDULA S.A.", None),
            233:	("CIFRA S.A.", None),
            745:	("CITIBANK", None),
            477:	("Citibank N.A.", None),
            90:	    ("COOPERATIVA CENTRAL DE CREDITO DO ESTADO DE SP", None),
            97:	    ("COOPERATIVA CENTRAL DE CREDITO NOROESTE BRASILEIRO", None),
            89:	    ("COOPERATIVA DE CREDITO RURAL DA REGIAO DA MOGIANA", None),
            75:	    ("CR2 S.A", None),
            98:	    ("CREDIALIANCA COOPERATIVA DE CREDITO RURAL", None),
            222:	("CREDIT AGRICOLE BRASIL S.A.", None),
            505:	("CREDIT SUISSE (BRASIL) S.A.", None),
            707:	("DAYCOVAL", None),
            487:	("DEUTSCHE BANK S. A. - BANCO ALEMAO", None),
            214:	("DIBENS S.A.", None),
            265:	("FATOR S.A.", None),
            224:	("FIBRA", None),
            626:	("FICSA S.A.", None),
            121:	("GERADOR S.A.", None),
            612:	("GUANABARA S.A.", None),
            62:	    ("HIPERCARD BANCO MULTIPLO S.A", None),
            399:	("HSBC", None),
            63:	    ("IBI", None),
            604:	("INDUSTRIAL DO BRASIL S. A.", None),
            653:	("INDUSVAL S.A.", None),
            492:	("ING BANK N.V.", None),
            630:	("INTERCAP S.A.", None),
            77:	    ("INTERMEDIUM S.A.", None),
            249:	("Investcred Unibanco", None),
            341:	("ITAÚ", None),
            652:	("ITAU HOLDING FINANCEIRA S.A", None),
            184:	("Itaú-BBA", None),
            74:	    ("J. SAFRA S.A.", None),
            376:	("J.P. MORGAN S.A.", None),
            217:	("JOHN DEERE S.A.", None),
            488:	("JPMORGAN CHASE BANK", None),
            76:	    ("KDB DO BRASIL S.A", None),
            757:	("KEB DO BRASIL S.A.", None),
            600:	("Luso Brasileiro", None),
            243:	("MAXIMA S.A.", None),
            389:	("MERCANTIL DO BRASIL", None),
            746:	("MODAL S.A.", None),
            66:	    ("MORGAN STANLEY DEAN WITTER S.A", None),
            14:	    ("NATIXIS BRASIL S.A. - BANCO MòLTIPLO", None),
            753:	("NBC BANK BRASIL S.A.- BANCO MULTIPLO", None),
            45:	    ("OPPORTUNITY S.A.", None),
            79:	    ("ORIGINAL DO AGRONEGOCIO S.A.", None),
            212:	("ORIGINAL S.A.", None),
            623:	("PANAMERICANO", None),
            254:	("PARANA BANCO S.A.", None),
            611:	("PAULISTA", None),
            613:	("PECUNIA S.A.", None),
            94:	    ("PETRA S.A.", None),
            643:	("PINE S.A.", None),
            735:	("POTTENCIAL S.A.", None),
            747:	("RABOBANK INTERNATIONAL BRASIL S.A.", None),
            88:	    ("RANDON S.A.", None),
            633:	("RENDIMENTO S.A.", None),
            741:	("RIBEIRÃO PRETO", None),
            120:	("RODOBENS S.A", None),
            453:	("RURAL", None),
            72:	    ("RURAL MAIS S.A", None),
            422:	("SAFRA", None),
            751:	("SCOTIABANK BRASIL S.A BANCO MULTIPLO", None),
            743:	("SEMEAR S.A.", None),
            748:	("SICREDI", None),
            749:	("SIMPLES S.A.", None),
            366:	("SOCIETE GENERALE BRASIL S.A", None),
            637:	("SOFISA S.A.", None),
            464:	("SUMITOMO MITSUI BRASILEIRO S.A.", None),
            82:	    ("TOPAZIO S.A.", None),
            634:	("Triangulo", None),
            230:	("UNICARD BANCO MULTIPLO S.A", None),
            91:	    ("UNICRED CENTRAL RS - CENTRAL DE COOP ECON CRED MUT", None),
            87:	    ("UNICRED CENTRAL SANTA CATARINA", None),
            99:	    ("UNIPRIME CENTRAL - CENTRAL INT DE COOP DE CRED LTD", None),
            655:	("VOTORANTIM", None),
            610:	("VR S.A.", None),
            119:	("WESTERN UNION DO BRASIL S.A.", None),
            124:	("WOORI BANK DO BRASIL S.A", None),
            136:	("Unicred", None)
    } 

fornecedores = {
            "Manutenção de Veiculos": ["DVA veiculos", "Victor dos santos", "furgoes isoppo", "Rf Comercio", "Posto de molas", "Mezaroba com", "Mecanica Rosso", "Duarte Diesel", "RF - Sul", "Obemolas", "Center Valvulas", "Scherer", "Energiluz"],
            "Manutenção e conservação predial": ["Madeireira uniao", "Oxi-genio", "dufrio", "Buachack", "Goedert LTDA", "Dominik", "Energiluz", "Rosso Materiais", "Guga gaz", "Energiluz"],
            "Manutenção de maquinas": ["Heth Maquinas", "Ambiente sul", "Maxus Impl", "Videfrigo", "Frigelar", "Guga gaz", "Dufrio"],
            "Peças corretivas": ["Scherer", "Valcanaia", "Disauto", "Atacado Diesel", "Casa do compressor", "Dva Veiculos", "center Valvulas", "Para-brisa", "P pneus", "Molas lambari", "buzetti", "Auto center", "Rex - radiadores", "Orbid S.A", "W C L Motopecas"],
            "Peças preventivas": ["Scherer", "Valcanaia", "Disauto", "Atacado Diesel", "Casa do compressor", "Dva Veiculos", "center Valvulas", "Para-brisa", "P pneus", "Molas lambari", "buzetti", "Auto center", "Rex - radiadores", "Orbid S.A", "W C L Motopecas"],
            "Combustivel e lubrificantes": ["Agricopel comercio", "Romano Diesel", "Planalto Com", "Rudnick", "Auto posto dallabona iii", "posto 4 irmaos", "marajo", "Nac Sul", "Maucor"],
            "Aluguéis": ["A&B locadora", "heth maquinas", "Macromaq", "Aluga maquinas Sul"],
            "Energia": ["Celesc", "Coop de energia eletrica", "Copel Distribuição"],
            "Agua e esgoto": ["Companhia Catarinense de Águas", "Sanepar ", "Semasa "],
            "Material limpeza": ["Goedert LTDA", "KL industria", "Mais clean", "KL produtos", "limpel "],
            "Serviços de terceiros": ["SBM renovadora", "A&E locadora", "Katia regina", "P4 Comunicação", "Rico lavação", "STZ Comunicação", "Hoff S.A", "P pneus serviços"],
            "Taxas": ["BSB comercio", "cento e um velocimetros"],
            "Despesas com refeitorio - Matriz": ["Camilo e tutumi", "Armazem agua", "Guga gaz", "Panificadora fazendinha", "Frutas na caixa"],
            "Material escritorio": ["Alexandre livramento", "Multwork comercial", "Contabilista suprimentos", "Reval atacado", "SRC embalagens"],
            "Despesas com Alimentação - Curitiba": ["Camilo e tutumi", "Armazem agua", "Guga gaz", "Panificadora fazendinha", "Frutas na caixa"],
            "Telefones": ["Claro S/A", "TIM S.A", "VIVO "],
            # Adicione outras categorias e fornecedores conforme necessário
            }
    
    
    
